### ISSUE TITLE
Adding Pictures and Information 

### ISSUE THREAD

**Issue by IC1101Virgo** [IC1101Virgo/AudreyHepburn#1]
I am making a gihub page on the British actress Audrey Hepburn. This is my first project to figure out the world of Git and usage.
**Anyone who wants to contribute is free too!**

**Comment by priyanshisharma** [comment]
Looks great @IC1101Virgo 🚀 I'm a little confused though, Are you trying to build a website to be hosted by Github pages? Or building a repository with `.md` files? 😅

**Comment by IC1101Virgo** [comment]
Hey @priyanshisharma ! I am building a website using GitHub Page. Sorry for the confusion it is my first time using these things 😝 . I was just messing with stuff seeing how I can use different tools available here.

**Comment by priyanshisharma** [comment]
Okayy! way to go!! 🚀 😃
